// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"os"
	"smartwallet-api/application/controllers"
)

// Injectors from wire.go:

func initRabbitMQClient() controllers.RabbitMQClient {
	config := provideConfig()
	rabbitMQClient := provideRabbitMQClient(config)
	return rabbitMQClient
}

// wire.go:

func provideConfig() Config {
	return Config{
		RabbitMQ: RabbitMQConfig{
			ConnectionString: os.Getenv("RABBIT_CONNECTIONSTRING"),
			QueueName:        os.Getenv("MARKETDATA_QUEUE_NAME"),
		},
	}
}

func provideRabbitMQClient(c Config) controllers.RabbitMQClient {
	return controllers.NewRabbitMQClient(c.RabbitMQ.ConnectionString)
}
