# Deploy to Azure Kubernetes Service

# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: GoTool@0
    inputs:
      version: '1.13.5'
    displayName: 'Install Go'
  - task: Go@0
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)/application'
    displayName: 'Build'
  - task: replacetokens@3
    inputs:
      targetFiles: '**/*.yaml'
      encoding: 'auto'
      writeBOM: false
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '__'
      tokenSuffix: '__'
      enableTelemetry: true
    displayName: 'Replace tokens'
  - task: Docker@2
    inputs:
      containerRegistry: 'smartwallet-6312'
      command: 'login'
    displayName: 'Log in Azure Container Registry'
  - task: Docker@2
    inputs:
      containerRegistry: 'smartwallet-6312'
      repository: 'smartwallet-api'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
    displayName: 'Build and Push Image'
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: '3.1.0'
    displayName: 'Helm Install'
  
  - task: HelmDeploy@0
    inputs:
      command: 'package'
      chartPath: '$(System.DefaultWorkingDirectory)/smartwallet-api-release/'
      destination: '$(Build.ArtifactStagingDirectory)'
      save: false
    displayName: 'Helm Package'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Artifact: Helm Package'
