apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartwallet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartwallet-api
  template:
    metadata:
      labels:
        app: smartwallet-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: smartwallet-api
        image: smartwallet.azurecr.io/smartwallet-api:__tag__
        env:
        - name: RABBIT_CONNECTIONSTRING
          valueFrom:
            configMapKeyRef:
              name: marketdata-api-config
              key: rabbitmq_connectionString
        - name: MARKETDATA_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: marketdata-api-config
              key: rabbitmq_marketdata_queue_name
        - name: MONGODB_CONNECTIONSTRING
          valueFrom:
            configMapKeyRef:
              name: smartwallet-api-config
              key: mongodb_connectionString
        ports:
        - containerPort: 19001
          name: smartwallet-api